version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: short_db
    restart: always
    env_file:
      - .env
    volumes:
      - ./short_db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '6500:5432'
    networks:
      - shared-network

  redis:
    image: redis:latest
    container_name: short_redis
    restart: always
    ports:
      - '6380:6379'
    volumes: 
      - short_redis:/data
    networks:
      - shared-network

  backend:
    container_name: short_backend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - shared-network

volumes:
  short_db:
  short_redis:

networks:
  shared-network:
