version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: short_db
    restart: always
    env_file:
      - .env
    volumes:
      - ./short_db:/var/lib/postgresql/data
    ports:
      - "6500:5432"

  redis:
    image: redis:latest
    container_name: short_redis
    restart: always
    ports:
      - '6400:6379'
    volumes: 
      - short_redis:/data

volumes:
  short_db:
  short_redis:
