version: '3.9'

services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - ./shortest_postgres_data:/var/lib/postgresql/data
    ports:
      - "1234:5432"
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - redis:/data

volumes:
  redis:
    driver: local

